# -*- coding: utf-8 -*-
"""CyAnalyst — 研报 Word 文档生成脚本

生成的文件输出到 scripts/output/research/{category}/ 目录，
文件名与 src/content/{category}/ 下的 Markdown 文件 ID 一一对应，
上传到 R2 后 URL 为: {R2_PUBLIC_URL}/research/{category}/{id}.docx
"""

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os


# ==================== 颜色常量 ====================
RED_UP = RGBColor(0xDC, 0x26, 0x26)
GREEN_DOWN = RGBColor(0x1A, 0x7A, 0x3A)
GRAY_FLAT = RGBColor(0x6B, 0x72, 0x80)


# ==================== 工具函数 ====================

def set_cell_shading(cell, color_hex):
    shading = OxmlElement('w:shd')
    shading.set(qn('w:fill'), color_hex)
    shading.set(qn('w:val'), 'clear')
    cell._tc.get_or_add_tcPr().append(shading)


def set_narrow_margins(doc):
    for section in doc.sections:
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)


def _set_font(run, size=10.5, bold=False, color=None):
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.name = 'Microsoft YaHei'
    run._element.rPr.rFonts.set(qn('w:eastAsia'), 'Microsoft YaHei')
    if color:
        run.font.color.rgb = color


def add_header_bar(doc, title, subtitle=""):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_font(p.add_run(title), size=22, bold=True, color=RED_UP)
    if subtitle:
        p2 = doc.add_paragraph()
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _set_font(p2.add_run(subtitle), size=12, color=GRAY_FLAT)
    doc.add_paragraph('_' * 60).alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()


def add_section_heading(doc, text):
    p = doc.add_paragraph()
    _set_font(p.add_run('_ ' + text), size=14, bold=True, color=RED_UP)


def add_paragraph(doc, text, bold=False, color=None, size=10.5):
    p = doc.add_paragraph()
    _set_font(p.add_run(text), size=size, bold=bold, color=color)
    p.paragraph_format.line_spacing = 1.5
    return p


def add_table_with_style(doc, headers, rows, col_widths=None):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = 'Table Grid'
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = h
        for p in cell.paragraphs:
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in p.runs:
                _set_font(run, size=9, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))
        set_cell_shading(cell, 'DC2626')
    for r_idx, row_data in enumerate(rows):
        for c_idx, val in enumerate(row_data):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = str(val)
            for p in cell.paragraphs:
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in p.runs:
                    _set_font(run, size=9)
            if r_idx % 2 == 0:
                set_cell_shading(cell, 'F9FAFB')
    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = Cm(w)
    doc.add_paragraph()


def add_kpi_box(doc, items):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for label, value, direction in items:
        if direction == 'up':
            color, arrow = RED_UP, '_ '
        elif direction == 'down':
            color, arrow = '_ '
        else:
            color, arrow = GRAY_FLAT, ''
        _set_font(p.add_run(f'{arrow}{label}: {value}    '), size=11, bold=True, color=color)
    doc.add_paragraph()


def add_disclaimer(doc):
    import datetime
    doc.add_paragraph('_' * 60)
    p = doc.add_paragraph()
    _set_font(p.add_run('Disclaimer: '), size=8, color=GRAY_FLAT)
    _set_font(p.add_run('Contents are for reference only and do not constitute investment advice.'), size=8, color=GRAY_FLAT)
    p2 = doc.add_paragraph()
    _set_font(p2.add_run(f'Generated by CyAnalyst - {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}'), size=8, color=GRAY_FLAT)


def save_report(doc, category: str, report_id: str):
    """保存研报到 scripts/output/research/{category}/{report_id}.docx"""
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output', 'research', category)
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f'{report_id}.docx')
    doc.save(out_path)
    print(f'[OK] {category}/{report_id}.docx -> {out_path}')
    return out_path


# ==================== 研报1：2026-06-24 早盘速览 ====================

def generate_2026_06_24_morning():
    doc = Document()
    set_narrow_margins(doc)
    add_header_bar(doc, 'CyAnalyst Morning Brief', '2026-06-24 | Pre-Market Preview')

    add_section_heading(doc, '1. Market Overview')
    add_paragraph(doc, 'A-share indices opened low and closed higher. Shanghai Composite +0.42%, Shenzhen Component +0.78%, ChiNext +1.05%. Total turnover reached 842 billion CNY, up 12% from the previous session. Northbound capital net inflow: 5.26 billion CNY (5th consecutive day).')

    add_table_with_style(doc,
        ['Index', 'Close', 'Change', 'Turnover (B)'],
        [['Shanghai', '3,287.62', '+0.42%', '4,218'],
         ['Shenzhen', '11,023.45', '+0.78%', '5,423'],
         ['ChiNext', '2,291.38', '+1.05%', '1,876']],
        col_widths=[3, 3, 2.5, 3])

    add_section_heading(doc, '2. Sector Performance')
    add_paragraph(doc, 'AI computing power led the market (+3.2%), driven by domestic AI chip production news. New energy (+1.8%) stabilized after recent correction. Consumer electronics (+1.5%) benefited from Q3 peak season expectations. Consumer sector (-0.5%) lagged.')

    add_table_with_style(doc,
        ['Sector', 'Change', 'Net Inflow (B)', 'Catalyst'],
        [['AI Computing', '+3.2%', '+68.2', 'Domestic chip breakthrough'],
         ['New Energy', '+1.8%', '+32.5', 'June sales beat expectations'],
         ['Consumer Elec', '+1.5%', '+18.6', 'Q3 peak season + Apple cycle'],
         ['Consumer', '-0.5%', '-12.1', 'Style rotation to growth']],
        col_widths=[3, 2, 3, 5])

    add_section_heading(doc, '3. Capital Flow')
    add_kpi_box(doc, [
        ('Northbound', '+5.26B', 'up'),
        ('Main Force', '+8.63B', 'up'),
        ('Margin', '1.52T', 'up'),
        ('Turnover', '842B', 'up'),
    ])

    add_section_heading(doc, '4. Strategy')
    add_paragraph(doc, '[Short-term]', bold=True, color=RED_UP)
    add_paragraph(doc, '1. AI Computing: Clear uptrend, buy on dips along 10-day MA. Focus on optical modules and servers.')
    add_paragraph(doc, '2. New Energy: June sales beat expectations but sector has rallied significantly. Hold, do not chase.')
    add_paragraph(doc, '3. Consumer Electronics: Q3 peak season + Apple cycle. Accumulate core supply chain names on weakness.')

    add_paragraph(doc, '[Medium-term]', bold=True, color=RED_UP)
    add_paragraph(doc, '1. F&B: Valuations back to reasonable range. Watch for Q2 earnings inflection, scale in gradually.')
    add_paragraph(doc, '2. Semiconductors: Domestic substitution + CIS price hikes. Medium-term thesis intact. Pullbacks are opportunities.')

    add_section_heading(doc, '5. Key Events Today')
    add_table_with_style(doc,
        ['Time', 'Event', 'Impact'],
        [['09:30', 'A-share open', 'All market'],
         ['10:00', 'PBOC OMO', 'Liquidity'],
         ['14:00', 'MIIT press conference', 'Tech/Manufacturing'],
         ['16:00', 'Northbound capital release', 'Capital flows']],
        col_widths=[2.5, 5, 4])

    add_disclaimer(doc)
    save_report(doc, 'daily', '2026-06-24-morning')


# ==================== 研报2：2026-06-23 盘后复盘 ====================

def generate_2026_06_23_evening():
    doc = Document()
    set_narrow_margins(doc)
    add_header_bar(doc, 'CyAnalyst Evening Review', '2026-06-23 | Close Analysis')

    add_section_heading(doc, '1. Closing Summary')
    add_paragraph(doc, 'Market showed "Shanghai weak, Shenzhen strong" pattern. Shanghai Composite dipped slightly while Shenzhen and ChiNext gained on new energy and semiconductor strength. Turnover contracted slightly, indicating cautious sentiment.')

    add_table_with_style(doc,
        ['Index', 'Close', 'Change', 'Turnover (B)', 'Technical'],
        [['Shanghai', '3,287.62', '-0.18%', '4,218', 'Testing 10-day MA'],
         ['Shenzhen', '11,023.45', '+0.67%', '5,423', 'Above 5-day MA'],
         ['ChiNext', '2,291.38', '+1.54%', '1,876', 'Volume breakout'],
         ['STAR 50', '1,056.83', '+2.12%', '687', 'Strong breakout']],
        col_widths=[2.5, 2.5, 2, 2.5, 3])

    add_section_heading(doc, '2. Sector Deep Dive')
    add_paragraph(doc, 'Semiconductor (+3.52%) led for 4th consecutive day with multiple stocks hitting yearly highs. PV equipment (+2.87%) and energy storage (+2.45%) also gained. Liquor (-1.23%) and banking (-0.76%) dragged.')

    add_table_with_style(doc,
        ['Sector', 'Change', 'Net (B)', 'Streak', 'Driver'],
        [['Semiconductors', '+3.52%', '+42.1', '4D up', 'Domestic substitution + CIS'],
         ['PV Equipment', '+2.87%', '+18.9', '2D up', 'Europe demand rebound'],
         ['Energy Storage', '+2.45%', '+12.6', 'Rebound', 'Policy catalyst'],
         ['Liquor', '-1.23%', '-15.7', '3D down', 'Sales data miss'],
         ['Banking', '-0.76%', '-9.8', '1D down', 'Rate cut pressure']],
        col_widths=[3, 2, 2.5, 2, 4])

    add_section_heading(doc, '3. Capital Flow Analysis')
    add_paragraph(doc, 'Northbound: Net inflow 5.26B CNY (Shanghai 1.82B, Shenzhen 3.44B). Shenzhen inflow significantly larger, consistent with today pattern.')
    add_paragraph(doc, 'Main force: Net inflow 8.63B CNY, of which super-large orders 6.21B. Institutional participation high.')
    add_paragraph(doc, 'Margin: Balance at 1.52T CNY, +2.86B from previous day. Short-selling remains minimal.')

    add_kpi_box(doc, [
        ('Northbound', '+5.26B', 'up'),
        ('Main Force', '+8.63B', 'up'),
        ('Margin Chg', '+0.29B', 'up'),
        ('A/D Ratio', '2876/1534', 'up'),
    ])

    add_section_heading(doc, '4. Technical Assessment')
    add_paragraph(doc, 'Shanghai Composite: Range-bound 3,250-3,330 for 12 sessions. MACD red bars shrinking. Break above 3,330 opens upside; break below 3,250 risks correction.')
    add_paragraph(doc, 'ChiNext: Volume breakout above 2,250 resistance. MACD golden cross forming. Next target: 2,350 (prior high).')

    add_section_heading(doc, '5. Tomorrow Strategy')
    add_paragraph(doc, '[Core View]', bold=True, color=RED_UP)
    add_paragraph(doc, 'Market at direction-selection window. Maintain "cautiously bullish" stance. Focus on structural opportunities in tech/growth.')

    add_paragraph(doc, '[Key Points]', bold=True, color=RED_UP)
    add_paragraph(doc, '1. Semiconductors: 4-day rally, entering overbought. Trim on strength, wait for pullback.')
    add_paragraph(doc, '2. New energy (PV + storage): Just starting rebound, still in positioning window.')
    add_paragraph(doc, '3. Consumer: Persistent weakness. Wait for Q2 earnings validation. No left-side bottom fishing yet.')
    add_paragraph(doc, '4. Position: Maintain 60-70%, keep cash for direction confirmation.')

    add_disclaimer(doc)
    save_report(doc, 'daily', '2026-06-23-evening')


# ==================== Main ====================

if __name__ == '__main__':
    generate_2026_06_24_morning()
    generate_2026_06_23_evening()
    print('\nAll reports generated.')
